services:
  postgres:
    image: postgres:16
    container_name: taskmasters-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskmasters
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taskmasters"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
