version: '3.8'

services:
  db:
    image: postgres:16
    container_name: taskmasters-db
    environment:
      # te wartości muszą zgadzać się z tym, co masz w application.properties
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskmasters
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taskmasters"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: taskmasters-backend
    ports:
      - "8080:8080"
    environment:
      # Spring DataSource
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmasters
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      # JWT properties
      APP_JWTSECRET: VerySecretKey123!
      APP_JWTEXPIRATIONMS: 86400000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
